
root: "/lhome/ific/a/aamerio/data_gluon/fermi"
OUT_LABEL: "test1"
week_in: 9
week_out: 30 #795
tmin: 0
tmax: 0
Emin: 100 # MeV # 0.5 GeV
Emax: 1000000 # MeV # 1000 GeV
Earr: [100, 1000, 10000, 100000, 1000000] # MeV
ZMAX : 90
EVCLASS: 2048
EVTYPE: 1
IRFS: 'P8R3_SOURCEVETO_V3'
nenergies: 2 # number of energies per bin, if Earr is specfied, else it's the total number of energies between Emin - Emax, in log scale
healpixorder: 11 #11
psf_theta_max: 30
psf_npoints: 6000 #number of points for the PSF
