
root: "/lhome/ific/a/aamerio/data/fermi"
OUT_LABEL: "sourceveto_nside2048_front_0.1_1000_GeV_w9-795"
week_in: 9
week_out: 795 #795
Emin: 100 # MeV # 0.5 GeV
Emax: 1000000 # MeV # 1000 GeV
Earr: [100, 1000, 10000, 100000, 1000000] # MeV
EVCLASS: 2048
EVTYPE: 1
IRFS: 'P8R3_SOURCEVETO_V3'
nenergies: 8 # number of energies per bin, if Earr is specfied, else it's the total number of energies between Emin - Emax, in log scale
healpixorder: 11 #11
